#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

include:
  - jobs.yml

name: Build OpenWrt - 22 - x86

env:
  REPO_BRANCH: v22.03.5 --depth=1
  CONFIG_FILE: 22-x86-xu.config

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'

jobs:
  hello:
    name: Say hello
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Print a greeting
        run: echo "Hello, world!"